[package]
name = "bench"
version = "0.1.0"
publish = false
authors = ["zTgx <beautifularea@163.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]

[[bin]]
name = "bench"
path = "src/bench.rs"